import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Link from "next/link";
import Loader from "../components/Loader";
import type { GetServerSideProps } from "next";
import { useRouter } from "next/router";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
const inter = Inter({ subsets: ["latin"] });
import { useTranslation } from "next-i18next";
import Modal from "../components/Modal";
import { useState } from "react";
import NavBar from '../components/navBar'
import Menu from "@/components/menu";
type Props = {
  // Add custom props here
};

function Home() {
  const { t } = useTranslation("common");
  const router = useRouter();
  const changeTo = router.locale === "en" ? "vi" : "en";
  const [showModal, setShowModal] = useState(false);
  const onToggleLanguageClick = (newLocale: string) => {
    const { pathname, asPath, query } = router;
    router.push({ pathname, query }, asPath, {
      locale: newLocale,
      scroll: false,
    });
  };

  return (
    <div className="wrapper" style={{ position: "relative" }}>
      <Head>
        <title>Nook Nails - Làm nail tại nhà theo cách của bạn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.svg" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
        <link
          href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"
          rel="stylesheet"
        />
      </Head>
      <Loader />
      <Menu onToggleLanguageClick={onToggleLanguageClick} />
      {/* banner-section */}
      <section className="banner-section">
        <div className="banner-carousel owl-theme owl-carousel owl-nav-none ">
          <div className="slide-item">
            <div
              className="image-layer"
              style={{
                backgroundImage: "url(/images/banner/banner1.webp)",
              }}
            />
            <div className="auto-container">
              <div className="content-box centred">
                <span className="slide-content">
                  <span
                    data-en="Relax and unwind with"
                    data-vn="Làm nails thư giãn"
                  >
                    {t("relax_and_unwind_with")}
                  </span>
                  <br />
                  <span
                    data-en="our at-home nail treatments"
                    data-vn="ngay tại nhà"
                  />
                  {t("at_home")}
                </span>
                <div className="btn-box" style={{ marginTop: 40 }}>
                  <div className="btn-center-container">
                    <Link href="/booking">
                      <Image
                        src="/images/icons/sparkle.gif"
                        alt=""
                        width={40}
                        height={40}
                      />
                      <button
                        data-en="BOOK NOW"
                        data-vn="ĐẶT LỊCH"
                        // data-tf-popup="LBToxE6v"
                        // data-tf-opacity={100}
                        // data-tf-size={100}
                        // data-tf-iframe-props="title=Làm Nails Cùng Nook"
                        // data-hj-allow-iframe=""
                        // data-tf-transitive-search-params=""
                        // data-tf-medium="snippet"
                        className="btn-typeform"
                      >
                        {t("book_now")}
                      </button>
                      <Image
                        src="/images/icons/sparkle.gif"
                        alt=""
                        width={40}
                        height={40}
                      />
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="slide-item">
            <div
              className="image-layer"
              style={{
                backgroundImage: "url(/images/banner/banner2.webp)",
              }}
            />
            <div className="auto-container">
              <div className="content-box centred">
                <span className="slide-content">
                  <span
                    data-en="Relax and unwind with"
                    data-vn="Làm nails thư giãn"
                  >
                    {t("relax_and_unwind_with")}
                  </span>
                  <br />
                  <span
                    data-en="our at-home nail treatments"
                    data-vn="ngay tại nhà"
                  >
                    {t("at_home")}
                  </span>
                </span>
                <div className="btn-box" style={{ marginTop: 40 }}>
                  <div className="btn-center-container">
                    <Link href="/booking">
                      <Image
                        src="/images/icons/sparkle.gif"
                        alt=""
                        width={40}
                        height={40}
                      />
                      <button
                        data-en="BOOK NOW"
                        data-vn="ĐẶT LỊCH"
                        // data-tf-popup="LBToxE6v"
                        // data-tf-opacity={100}
                        // data-tf-size={100}
                        // data-tf-iframe-props="title=Làm Nails Cùng Nook"
                        // data-hj-allow-iframe=""
                        // data-tf-transitive-search-params=""
                        // data-tf-medium="snippet"
                        className="btn-typeform"
                      >
                        {t("book_now")}
                      </button>
                      <Image
                        src="/images/icons/sparkle.gif"
                        alt=""
                        width={40}
                        height={40}
                      />
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="slide-item">
            <div
              className="image-layer"
              style={{
                backgroundImage: "url(/images/banner/banner3.webp)",
              }}
            />
            <div className="auto-container">
              <div className="content-box centred">
                <span className="slide-content">
                  <span
                    data-en="Relax and unwind with"
                    data-vn="Làm nails thư giãn"
                  >
                    {t("relax_and_unwind_with")}
                  </span>
                  <br />
                  <span
                    data-en="our at-home nail treatments"
                    data-vn="ngay tại nhà"
                  >
                    {t("at_home")}
                  </span>
                </span>
                <div className="btn-box" style={{ marginTop: 40 }}>
                  <div className="btn-center-container">
                    <Link href="/booking">
                      <Image
                        src="/images/icons/sparkle.gif"
                        alt=""
                        width={40}
                        height={40}
                      />
                      <button
                        data-en="BOOK NOW"
                        data-vn="ĐẶT LỊCH"
                        // data-tf-popup="LBToxE6v"
                        // data-tf-opacity={100}
                        // data-tf-size={100}
                        // data-tf-iframe-props="title=Làm Nails Cùng Nook"
                        // data-hj-allow-iframe=""
                        // data-tf-transitive-search-params=""
                        // data-tf-medium="snippet"
                        className="btn-typeform"
                      >
                        {t("book_now")}
                      </button>
                      <Image
                        src="/images/icons/sparkle.gif"
                        alt=""
                        width={40}
                        height={40}
                      />
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="end-banner-section">
          <div className="end-banner-container">
            <div className="end-banner-item">
              <Image
                className="start-icon"
                src="/images/icons/star-yellow.svg"
                alt=""
                width={26}
                height={26}
              />
              <div>
                <span
                  data-en="GEL POLISH"
                  data-vn="SƠN GEL"
                  className="item-content-first"
                >
                  {t("gel_polish")}
                </span>
              </div>
              <div>
                <span
                  data-en="High quality"
                  data-vn="Chất lượng"
                  className="item-content-second"
                >
                  {t("high_quality")}
                </span>
              </div>
            </div>
            <div className="end-banner-item">
              <Image
                className="start-icon"
                src="/images/icons/star-yellow.svg"
                alt=""
                width={26}
                height={26}
              />
              <div>
                <span
                  data-en="TRAVEL EXPENSES"
                  data-vn="PHÍ ĐI LẠI"
                  className="item-content-first"
                >
                  {t("travel_expenses")}
                </span>
              </div>
              <div>
                <span
                  data-en="Free"
                  data-vn="Miễn phí"
                  className="item-content-second"
                >
                  {t("free")}
                </span>
              </div>
            </div>
            <div className="end-banner-item">
              <Image
                className="start-icon"
                src="/images/icons/star-yellow.svg"
                alt=""
                width={26}
                height={26}
              />
              <div>
                <span
                  data-en="NAILS WARRANTY"
                  data-vn="BẢO HÀNH NAILS"
                  className="item-content-first"
                >
                  {t("nail_warranty")}
                </span>
              </div>
              <div>
                <span
                  data-en="3 days"
                  data-vn="3 ngày"
                  className="item-content-second"
                >
                  {t("3_days")}
                </span>
              </div>
            </div>
            <div className="end-banner-item">
              <Image
                className="start-icon"
                src="/images/icons/star-yellow.svg"
                alt=""
                width={26}
                height={26}
              />
              <div>
                <span
                  data-en="MATCH DESIGN"
                  data-vn="THIẾT KẾ MẪU GIỐNG"
                  className="item-content-first"
                >
                  {t("match_design")}
                </span>
              </div>
              <div>
                <span
                  data-en="Up to 90%"
                  data-vn="Đến 90%"
                  className="item-content-second"
                >
                  {t("up_to_90")}
                </span>
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* banner-section end */}

      <section id="experience-section" className="experience-section">
        <div className="auto-container">
          <div className="sec-title brown">
            <Image
              className="start-icon-grey"
              src="/images/icons/star-grey.svg"
              alt=""
              width={18}
              height={18}
            />
            <div className="experience-content">
              <span data-vn="TRẢI NGHIỆM" data-en="EXPERIENCE">
                {t("experience")}
              </span>
            </div>
            <div className="experience-content-second">
              <span data-vn="Sự tiện lợi" data-en="Convenience">
                {t("convenience")}
              </span>
            </div>
          </div>
          <div className="row clearfix experience-service">
            {changeTo === "en" ? (
              <>
                {/* <Image
                  className="experience-service-img-web"
                  src="/images/service/experience-service.png"
                  alt=""
                  width={1200}
                  height={585}
                  quality={100}
                />
                <Image
                  className="experience-service-img"
                  src="/images/service/experience-service.mobile-en.png"
                  alt=""
                  fill
                  quality={100}
                /> */}
                <img src="/images/service/experience-service.png" className="experience-service-img-web"></img>
                <img src="/images/service/experience-service.mobile.png" className="experience-service-img"></img>

              </>
            ) : (
              <>
                <img src="/images/service/experience-service-en.png" className="experience-service-img-web"></img>
                <img src="/images/service/experience-service.mobile-en.png" className="experience-service-img"></img>
                {/* <Image
                  className="experience-service-img-web"
                  src="/images/service/experience-service-en.png"
                  alt=""
                  width={1200}
                  height={585}
                  quality={100}
                />
                <Image
                  className="experience-service-img"
                  src="/images/service/experience-service.mobile.png"
                  alt=""
                  fill
                  quality={100}
                /> */}
              </>
            )}
          </div>
          <div className="more-btn centred">
            <div className="btn-center-container">
              <Link href="/booking">
                <Image
                  src="/images/icons/sparkle.gif"
                  alt=""
                  width={40}
                  height={40}
                />
                <button
                  data-en="Book now"
                  data-vn="Đặt lịch"
                  style={{ backgroundColor: "#231E1E" }}
                  // data-tf-popup="LBToxE6v"
                  // data-tf-opacity={100}
                  // data-tf-size={100}
                  // data-tf-iframe-props="title=Làm Nails Cùng Nook"
                  // data-hj-allow-iframe=""
                  // data-tf-transitive-search-params=""
                  // data-tf-medium="snippet"
                  className="btn-typeform"
                >
                  {t("book_now")}
                </button>
                <Image
                  src="/images/icons/sparkle.gif"
                  alt=""
                  width={40}
                  height={40}
                />
              </Link>
            </div>
          </div>
        </div>
      </section>
      <>
        {/* prices-section */}
        <section id="prices-section" className="prices-section">
          <div className="auto-container">
            <div className="sec-title brown">
              {/* <span style="font-family: Dancing Script;line-height: 80px;color:#FAE3D7">Tại nhà</span> */}
              <Image
                className="start-icon-grey"
                src="/images/icons/star-grey.svg"
                alt=""
                width={18}
                height={18}
              />
              <div className="experience-content">
                <span
                  data-en="NAIL SALON EXPERIENCE"
                  data-vn="MANG NAIL SALON ĐẾN"
                >
                  {t("nail_salon_exp")}
                </span>
              </div>
              <div className="experience-content-second">
                <span data-en="At home" data-vn="Nhà bạn">
                  {t("_at_home")}
                </span>
              </div>
            </div>
            <div style={{ textAlign: "center" }}>
              <video
                itemProp="video"
                // itemScope=""
                itemType="http://schema.org/VideoObject"
                width={600}
                height="auto"
                style={{ borderRadius: 8 }}
                autoPlay={true}
                muted={true}
                loop={true}
              >
                <source src="/videos/service.mp4" type="video/mp4" />
                <meta itemProp="duration" content="T1M30S" />
                <meta
                  itemProp="thumbnailUrl"
                  content="https://nails.workwithnook.com/assets/images/thumbnails/video.jpg"
                />
                <meta
                  itemProp="uploadDate"
                  content="2023-04-14T10:00:00-08:00"
                />
              </video>
            </div>
            <div
              style={{ textAlign: "center" }}
              className="column prices-section-content"
            >
              {changeTo === "en" ? (
                // <Image
                //   className="prices-section-img"
                //   src="/images/resource/Feature-Preparison-3.png"
                //   width={600}
                //   height={500}
                //   alt={""}
                // />
                <img src="/images/resource/Feature-Preparison-3.png" className="prices-section-img" />
              ) : (
                <img src="/images/resource/Feature-Preparison-3-en.png" className="prices-section-img" />
                // <Image
                //   className="prices-section-img"
                //   src="/images/resource/Feature-Preparison-3-en.png"
                //   width={600}
                //   height={500}
                //   alt={""}
                // />
              )}
            </div>
            <div className="text-center">
              <div className="btn-center-container">
                <Image
                  src="/images/icons/sparkle.gif"
                  alt=""
                  width={40}
                  height={40}
                />
                <button
                  className="btn-typeform-menu"
                  style={{ backgroundColor: "#231E1E" }}
                >
                  <Link
                    data-en="View Process"
                    data-vn="Xem Quy Trình"
                    href="/images/process/web/Process.web.1.webp"
                    className="lightbox-image text-white"
                    data-fancybox="process"
                  >
                    {t("view_process")}
                  </Link>
                </button>
                <Image
                  src="/images/icons/sparkle.gif"
                  alt=""
                  width={40}
                  height={40}
                />
              </div>
            </div>
            <div id="process" className="d-none">
              <Link
                href="/images/process/web/Process.web.2.webp"
                className="lightbox-image"
                data-fancybox="process"
              />
              <Link
                href="/images/process/web/Process.web.3.webp"
                className="lightbox-image"
                data-fancybox="process"
              />
              <Link
                href="/images/process/web/Process.web.4.webp"
                className="lightbox-image"
                data-fancybox="process"
              />
              <Link
                href="/images/process/web/Process.web.5.webp"
                className="lightbox-image"
                data-fancybox="process"
              />
              <Link
                href="/images/process/web/Process.web.6.webp"
                className="lightbox-image"
                data-fancybox="process"
              />
            </div>
          </div>
        </section>
        {/* prices-section end */}
        {/* gallery-section */}
        <section id="gallery-section" className="gallery-section bg-color-1">
          <div className="outer-container">
            <div className="sec-title brown">
              <Image
                className="start-icon-grey"
                src="/images/icons/star-grey.svg"
                alt=""
                width={18}
                height={18}
              />
              <div className="experience-content">
                <span
                  data-en="OUR LASTEST COLLECTION"
                  data-vn="BỘ SƯU TẬP MỚI NHẤT"
                >
                  {t("latest_collection")}
                </span>
              </div>
              <div className="experience-content-second">
                <span data-en="Nook Nails" data-vn="Nook Nails">
                  Nook Nails
                </span>
              </div>
            </div>
            <div className="gallery-carousel owl-carousel owl-theme owl-nav-none owl-dots-style-one">
              <div className="gallery-block-one">
                <div className="inner-box">
                  <figure className="image-box">
                    <Image
                      src="/images/gallery/gallery-1.jpeg"
                      alt=""
                      width={400}
                      height={400}
                    />
                    <Link
                      href="/images/gallery/gallery-1.jpeg"
                      className="lightbox-image"
                      data-fancybox="gallery"
                    >
                      <i className="flaticon-plus-1" />
                    </Link>
                  </figure>
                </div>
              </div>
              <div className="gallery-block-one">
                <div className="inner-box">
                  <figure className="image-box">
                    <Image
                      src="/images/gallery/gallery-2.webp"
                      alt=""
                      width={400}
                      height={400}
                    />
                    <Link
                      href="/images/gallery/gallery-2.webp"
                      className="lightbox-image"
                      data-fancybox="gallery"
                    >
                      <i className="flaticon-plus-1" />
                    </Link>
                  </figure>
                </div>
              </div>
              <div className="gallery-block-one">
                <div className="inner-box">
                  <figure className="image-box">
                    <Image
                      src="/images/gallery/gallery-3.webp"
                      alt=""
                      width={400}
                      height={400}
                    />
                    <Link
                      href="/images/gallery/gallery-3.webp"
                      className="lightbox-image"
                      data-fancybox="gallery"
                    >
                      <i className="flaticon-plus-1" />
                    </Link>
                  </figure>
                </div>
              </div>
              <div className="gallery-block-one">
                <div className="inner-box">
                  <figure className="image-box">
                    <Image
                      src="/images/gallery/gallery-4.webp"
                      alt=""
                      width={400}
                      height={400}
                    />
                    <Link
                      href="/images/gallery/gallery-4.webp"
                      className="lightbox-image"
                      data-fancybox="gallery"
                    >
                      <i className="flaticon-plus-1" />
                    </Link>
                  </figure>
                </div>
              </div>
              <div className="gallery-block-one">
                <div className="inner-box">
                  <figure className="image-box">
                    <Image
                      src="/images/gallery/gallery-5.webp"
                      alt=""
                      width={400}
                      height={400}
                    />
                    <Link
                      href="/images/gallery/gallery-5.webp"
                      className="lightbox-image"
                      data-fancybox="gallery"
                    >
                      <i className="flaticon-plus-1" />
                    </Link>
                  </figure>
                </div>
              </div>
              <div className="gallery-block-one">
                <div className="inner-box">
                  <figure className="image-box">
                    <Image
                      src="/images/gallery/gallery-6.webp"
                      alt=""
                      width={400}
                      height={400}
                    />
                    <Link
                      href="/images/gallery/gallery-6.webp"
                      className="lightbox-image"
                      data-fancybox="gallery"
                    >
                      <i className="flaticon-plus-1" />
                    </Link>
                  </figure>
                </div>
              </div>
            </div>
            <div className="gallery-menu">
              <div
                className="container-lg"
                style={{ 
                  display: "flex", 
                  justifyContent: "center",
                  margin: "0px",
                  padding: "0px",
                  maxWidth: "1200px" }}
              >
                {/* <div class="menu-carousel owl-carousel owl-theme"> */}
                <div
                  id="menu-combo"
                  className="img-hover-effect menu-website"
                  style={{ maxWidth: 1200 }}
                  onClick={() => setShowModal(true)}
                >
                  {changeTo === "en" ? (
                    // <Image
                    //   style={{ maxWidth: 800 }}
                    //   src="/images/menu/Menu-combo-website.webp"
                    //   width={800}
                    //   height={400}
                    //   alt=""
                    // />
                    <img src="/images/menu/Menu-combo-website.webp" style={{ maxWidth: "1200px", width: "100%" }} />
                  ) : (
                    // <Image
                    //   style={{ maxWidth: 800 }}
                    //   src="/images/menu/Menu-combo-website-en.webp"
                    //   width={800}
                    //   height={400}
                    //   alt=""
                    // />
                    <img src="/images/menu/Menu-combo-website-en.webp" style={{ maxWidth: "1200px", width: "100%" }} />
                  )}
                </div>
                <div
                  className="img-hover-effect menu-mobile"
                  style={{ maxWidth: 800 }}
                >
                  {changeTo === "en" ? (
                    // <Image
                    //   style={{ maxWidth: 320 }}
                    //   src="/images/menu/Menu-combo-mobile.webp"
                    //   alt=""
                    //   width={320}
                    //   height={200}
                    // />
                    <img src="/images/menu/Menu-combo-mobile-en.webp" style={{ maxWidth: "800px", width: "100%" }} />

                  ) : (
                    // <Image
                    //   style={{ maxWidth: 320 }}
                    //   src="/images/menu/Menu-combo-mobile-en.webp"
                    //   alt=""
                    //   width={320}
                    //   height={200}
                    // />
                    <img src="/images/menu/Menu-combo-mobile-en.webp" style={{ maxWidth: "800px", width: "100%" }} />

                  )}
                </div>
                {/* <div id="menu" class="img-hover-effect">
                          <img src="assets/images/menu/Menu.png" alt="">
                      </div> */}
                {/* </div> */}
              </div>
            </div>
            <div className="more-btn centred">
              <div className="btn-center-container">
                <Link href="/booking">
                  <Image
                    src="/images/icons/sparkle.gif"
                    alt=""
                    width={40}
                    height={40}
                  />
                  <button
                    data-en="Book now"
                    data-vn="Đặt lịch"
                    // data-tf-popup="LBToxE6v"
                    // data-tf-opacity={100}
                    // data-tf-size={100}
                    // data-tf-iframe-props="title=Làm Nails Cùng Nook"
                    // data-hj-allow-iframe=""
                    // data-tf-transitive-search-params=""
                    // data-tf-medium="snippet"
                    className="btn-typeform-menu"
                    style={{ backgroundColor: "#231E1E" }}
                  >
                    {t("book_now")}
                  </button>
                  <Image
                    src="/images/icons/sparkle.gif"
                    alt=""
                    width={40}
                    height={40}
                  />
                </Link>
              </div>
            </div>
          </div>
        </section>
        {/* team-section */}
        <section id="team-section" className="team-section">
          {/* <div class="pattern-layer" style="background-image: url(assets/images/shape/shape-3.png);"></div> */}
          <div className="auto-container">
            <div className="sec-title brown">
              <Image
                className="start-icon-grey"
                src="/images/icons/star-grey.svg"
                alt=""
                width={18}
                height={18}
              />
              <div className="experience-content">
                <span data-en="REVIEWS FROM" data-vn="CẢM NHẬN">
                  {t("review")}
                </span>
              </div>
              <div className="experience-content-second">
                <span data-en="Customers" data-vn="Khách hàng">
                  {t("customers")}
                </span>
              </div>
            </div>
            <div id="team-section-content" className="team-section-content">
              <div className="team-block">
                <div className="team-block-one">
                  <div className="inner-box">
                    <figure className="image-box">
                      <Image
                        src="/images/customer/customer_1.png"
                        alt=""
                        width={360}
                        height={360}
                      />
                      {/* <span class="signature">Nguyễn thị a</span> */}
                    </figure>
                    <div className="lower-content">
                      <h5>
                        <a>Hà Lê</a>
                      </h5>
                      <p
                        data-en='"The technician did a fantastic job of carefully and cleanly cutting my skin. 
                              She also applied top-notch gel nail polish and my nails have been intact for more than a month ^^."'
                        data-vn='"Đặt được 1 bạn cắt da sạch và cẩn thận, lại còn sử dụng chất sơn gel xịn. Mình
                              giữ móng cũng được hơn 1 tháng rưỡi rồi ^^"'
                      >
                        {t("review_1")}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="team-block">
                <div className="team-block-one">
                  <div className="inner-box">
                    <figure className="image-box">
                      <Image
                        src="/images/customer/customer_2.png"
                        alt=""
                        width={360}
                        height={360}
                      />
                      {/* <span class="signature">Nguyễn thị a</span> */}
                    </figure>
                    <div className="lower-content">
                      <h5>
                        <a>Vy Trần</a>
                      </h5>
                      <p
                        data-en='"Getting my nails done at the salon can be tiring, especially when I have to wait others. 
                              Meanwhile, having the technician come to my home means they focus on me, which speeds up the process 
                              and makes it more enjoyable. Best of all, I get to sit back and relax at my own home."'
                        data-vn='"Làm ở tiệm mệt lắm, còn phải chờ đợi người khác nên nhiều khi làm ẩu. Ở nhà thì
                              thợ chỉ tập trung vào mình thôi nên nhanh, đẹp hơn. Chưa kể ở nhà mình có không
                              gian riêng tư thoải mái."'
                      >
                        {t("review_2")}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="team-block">
                <div className="team-block-one">
                  <div className="inner-box">
                    <figure className="image-box">
                      <Image
                        src="/images/customer/customer_3.png"
                        alt=""
                        width={360}
                        height={360}
                      />
                      {/* <span class="signature">Nguyễn thị a</span> */}
                    </figure>
                    <div className="lower-content">
                      <h5>
                        <a>Ngọc Trang</a>
                      </h5>
                      <p
                        data-en='"I was pleasant when the technician suggested a simple yet elegant nail design that perfectly 
                              matched my dress for my BFF&apos;s wedding. I received many compliments, and it was a great experience overall."'
                        data-vn='"Book dịch vụ ở Nook vào đúng dịp đám cưới đứa bạn thân, được chị chuyên viên tư
                              vấn cho bộ nail đơn giản thanh lịch mà phù hợp với váy vô cùng."'
                      >
                        {t("review_3")}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* team-section end */}
        {/* cta-section */}
        <section
          className="cta-section"
          style={{
            backgroundImage: "url(/images/footer/Bottom-Banner-BG-Web.svg)",
            backgroundPosition: "center center",
          }}
        >
          {/* <img class="cta-img-web" src="assets/images/footer/Bottom-Banner-BG-Web.svg" alt=""> */}
          {/* <img class="cta-img-mobile" src="assets/images/footer/Bottom-Banner-BG-Mobile.svg" alt=""> */}
          <div className="auto-container">
            <div
              className=" clearfix"
              style={{
                textAlign: "center",
                paddingTop: 65,
                paddingBottom: 65,
              }}
            >
              <div className="cta-content">
                <span>
                  <span
                    data-en="Reserve your spot and receive a"
                    data-vn="Đặt lịch ngay để nhận ưu đãi"
                  >
                    {t("reserver_your_spot")}
                  </span>
                  <p />
                  <span data-en="special offer" data-vn="từ Nook Nails">
                    {t("special_offer")}
                  </span>
                </span>
              </div>
              <div className="btn-center-container">
                <Link href="/booking">
                  <Image
                    src="/images/icons/sparkle.gif"
                    alt=""
                    width={18}
                    height={18}
                  />
                  <button
                    data-en="Book now"
                    data-vn="Đặt lịch"
                    // data-tf-popup="LBToxE6v"
                    // data-tf-opacity={100}
                    // data-tf-size={100}
                    // data-tf-iframe-props="title=Làm Nails Cùng Nook"
                    // data-hj-allow-iframe=""
                    // data-tf-transitive-search-params=""
                    // data-tf-medium="snippet"
                    className="btn-typeform-menu"
                    style={{ backgroundColor: "#231E1E" }}
                  >
                    {t("book_now")}
                  </button>
                  <Image
                    src="/images/icons/sparkle.gif"
                    alt=""
                    width={18}
                    height={18}
                  />
                </Link>
              </div>
            </div>
          </div>
        </section>
        {/* cta-section end */}
        {/* main-footer */}
        <footer className="main-footer">
          <div className="footer-botton">
            <div className="auto-container clearfix">
              <div className="copyright pull-left">
                © 2023 Nook. All right service
              </div>
              <ul className="footer-social pull-right clearfix">
                <div className="phone-number">
                  <Image
                    src="/images/icons/phone.svg"
                    alt=""
                    width={27}
                    height={27}
                  />
                  <a target="_blank" href="tel:1900633897">
                    <span>1900 633 897</span>
                  </a>
                </div>
                <div className="facebook social-item">
                  <a
                    href="https://www.facebook.com/nailswithnook"
                    target="_blank"
                  >
                    <Image
                      src="/images/icons/facebook.svg"
                      alt=""
                      width={24}
                      height={24}
                    />
                  </a>
                </div>
              </ul>
            </div>
          </div>
        </footer>
        {/* main-footer end */}

        {/* Social widget */}
        <div className="social-widget">
          <div className="social-widget-item">
            <a href="https://zalo.me/g/aiveia597" target="_blank">
              <Image
                src="/images/icons/zalo.svg"
                alt=""
                width={25}
                height={24}
                quality={100}
              />
            </a>
          </div>
          <div className="social-widget-item">
            <a target="_blank" href="tel:1900633897">
              <svg
                width={19}
                height={19}
                viewBox="0 0 19 19"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M18.332 1.12891L14.6758 0.285156C14.2891 0.179688 13.8672 0.390625 13.6914 0.777344L12.0039 4.71484C11.8633 5.06641 11.9688 5.45312 12.25 5.69922L14.3945 7.45703C13.1289 10.1289 10.9141 12.3789 8.17188 13.6797L6.41406 11.5352C6.16797 11.2539 5.78125 11.1484 5.42969 11.2891L1.49219 12.9766C1.10547 13.1523 0.929688 13.5742 1 13.9609L1.84375 17.6172C1.94922 18.0039 2.26562 18.25 2.6875 18.25C11.6875 18.25 19 10.9727 19 1.9375C19 1.55078 18.7188 1.23438 18.332 1.12891Z"
                  fill="black"
                />
              </svg>
            </a>
          </div>
          <div className="social-widget-item">
            <Link href="/booking">
              <button
              // data-tf-popup="LBToxE6v"
              // data-tf-opacity={100}
              // data-tf-size={100}
              // data-tf-iframe-props="title=Làm Nails Cùng Nook"
              // data-hj-allow-iframe=""
              // data-tf-transitive-search-params=""
              // data-tf-medium="snippet"
              >
                <Image
                  src="/images/icons/calendar.svg"
                  alt=""
                  width={18}
                  height={18}
                />
                <span data-en="Book now" data-vn="Đặt lịch">
                  {t("book_now")}
                </span>
              </button>
            </Link>
          </div>
        </div>
        <Modal title="" onClose={() => setShowModal(false)} show={showModal}>
          {changeTo === 'en' ? <Image
            src="/images/menu/Menu-combo-website.png"
            alt=""
            width={1200}
            height={600}
          /> : <Image
            src="/images/menu/Menu-combo-website-en.webp"
            alt=""
            width={1200}
            height={600}
          />}
        </Modal>
      </>
    </div>
  );
}

export const getServerSideProps = async ({ locale }: { locale: string }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? "vi", ["common"])),
    }, // will be passed to the page component as props
  };
};

export default Home;
